export const LOG_IN_START = "LOG_IN_START";
export const LOG_IN = "LOG_IN";
export const LOG_OUT = "LOG_OUT";
export const LOG_IN_SUCCESS = "LOG_IN_SUCCESS";
export const LOG_IN_LOADING_OFF = "LOG_IN_LOADING_OFF";

export const GET_DATA_E_I = "GET_DATA_E_I";
export const SET_DATA_EXP = "SET_DATA_EXP";
export const SET_DATA_INC = "SET_DATA_INC";
export const SET_DATA_COMPLECTS = "SET_DATA_COMPLECTS";
export const SET_DATA_AVAILABLE_COMPLECTS = "SET_DATA_AVAILABLE_COMPLECTS";
export const CREATE_FORM_LISTS = "CREATE_FORM_LISTS";

export const CREATE_EXP_TABLE = "CREATE_EXP_TABLE";
export const CREATE_INC_TABLE = "CREATE_INC_TABLE";
export const COUNT_TOTAL_STATS = "COUNT_TOTAL_STATS";
export const CHECK_FOR_INC_ERRORS = "CHECK_FOR_INC_ERRORS";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";
